import { MortonKey } from "../../math/morton-key.js";
import { VoxelChunk } from "../chunks/voxel-chunk.js";
import { BVXLayer } from "../layer/bvx-layer.js";
import { VoxelWorld } from "../voxel-world.js";

/**
 * VoxelSmoothGeometry generates a smooth, renderer-agnostic triangle mesh for the
 * BitVoxels of a VoxelChunk using the Naive Surface Nets algorithm. This is an
 * alternative to the blocky VoxelFaceGeometry + BVXGeometry rendering path.
 *
 * The mesh is computed from a scalar occupancy field sampled from the chunk and
 * its neighbouring chunks. An optional number of smoothing passes blurs the field
 * before contouring, producing progressively softer, blobbier surfaces. With no
 * smoothing the result is the classic surface nets mesh with edge-midpoint
 * crossings.
 *
 * Design notes:
 *
 * - Geometry is emitted in the same coordinate space as BVXGeometry, where a
 *   single Voxel spans 1.0 units and a BitVoxel spans 0.25 units. A chunk covers
 *   0.0 to 4.0 units on each axis.
 * - Chunk seams are watertight. The occupancy field is sampled from neighbouring
 *   chunks so both sides of a seam contour identical data, and seam quads are
 *   emitted by exactly one of the two chunks (ownership goes to the negative-side
 *   chunk when it exists in the world).
 * - Normals are derived from the field gradient at each surface cell, which is
 *   local to the cell and therefore consistent on both sides of a chunk seam.
 * - Like other geometry classes, instances pre-allocate worst-case buffers once
 *   and can be reused across computeGeometry() calls without further allocations.
 */
export class VoxelSmoothGeometry {
    /**
     * The maximum number of supported smoothing passes.
     */
    public static readonly MAX_SMOOTHING: number = 3;

    /**
     * The size of a single BitVoxel in output coordinate space, matching the
     * BVXGeometry lookup tables (4 BitVoxels per 1.0 unit Voxel).
     */
    public static readonly BIT_VOXEL_SIZE: number = 0.25;

    /**
     * The maximum field sampling margin around the chunk. Each smoothing pass
     * consumes one sample of margin, plus one sample for the border surface cells.
     */
    private static readonly _MARGIN_MAX: number = 1 + VoxelSmoothGeometry.MAX_SMOOTHING;

    /**
     * The dimensions of the field sampling buffer at maximum margin.
     */
    private static readonly _FIELD_DIMS: number = BVXLayer.DIMS + (2 * VoxelSmoothGeometry._MARGIN_MAX);

    /**
     * The dimensions of the surface cell grid. Cells with min-corner from -1 to 15
     * on each axis are contoured, which covers the negative seams of the chunk.
     */
    private static readonly _CELL_DIMS: number = BVXLayer.DIMS + 1;

    /**
     * The maximum number of surface cells (and therefore vertices) per chunk.
     */
    private static readonly _MAX_CELLS: number = VoxelSmoothGeometry._CELL_DIMS * VoxelSmoothGeometry._CELL_DIMS * VoxelSmoothGeometry._CELL_DIMS;

    /**
     * The maximum number of indices per chunk. Each of the 3 edge directions has
     * 17x16x16 candidate edges, each emitting at most one quad (6 indices).
     */
    private static readonly _MAX_INDICES: number = 3 * VoxelSmoothGeometry._CELL_DIMS * BVXLayer.DIMS * BVXLayer.DIMS * 6;

    /**
     * The iso-level of the occupancy field. Field values at or above this level
     * are considered inside the surface.
     */
    private static readonly _ISO_LEVEL: number = 0.5;

    /**
     * Temporary MortonKey used for neighbouring chunk queries.
     */
    private static readonly TMP_MK: MortonKey = new MortonKey();

    /**
     * The occupancy field sampled from the chunk and its neighbours.
     */
    private readonly _field: Float32Array;

    /**
     * Scratch buffer used during field smoothing passes.
     */
    private readonly _fieldScratch: Float32Array;

    /**
     * Maps a surface cell to its vertex index, or -1 when the cell has no vertex.
     */
    private readonly _cellVertex: Int32Array;

    /**
     * Vertex positions (3 floats per vertex).
     */
    private readonly _vertices: Float32Array;

    /**
     * Vertex normals (3 floats per vertex).
     */
    private readonly _normals: Float32Array;

    /**
     * Triangle indices (3 indices per triangle).
     */
    private readonly _indices: Uint32Array;

    /**
     * The number of vertices generated by the most recent computeGeometry() call.
     */
    private _vertexCount = 0;

    /**
     * The number of indices generated by the most recent computeGeometry() call.
     */
    private _indexCount = 0;

    /**
     * The number of vertices whose field gradient was degenerate (zero) and
     * require a triangle-accumulated normal fallback.
     */
    private _degenerateNormalCount = 0;

    constructor() {
        const fieldSize: number = VoxelSmoothGeometry._FIELD_DIMS * VoxelSmoothGeometry._FIELD_DIMS * VoxelSmoothGeometry._FIELD_DIMS;

        this._field = new Float32Array(fieldSize);
        this._fieldScratch = new Float32Array(fieldSize);
        this._cellVertex = new Int32Array(VoxelSmoothGeometry._MAX_CELLS);
        this._vertices = new Float32Array(VoxelSmoothGeometry._MAX_CELLS * 3);
        this._normals = new Float32Array(VoxelSmoothGeometry._MAX_CELLS * 3);
        this._indices = new Uint32Array(VoxelSmoothGeometry._MAX_INDICES);
    }

    /**
     * Returns the vertex positions generated by the most recent computeGeometry()
     * call as an exact-length view (3 floats per vertex).
     *
     * NOTE: The returned view aliases an internal buffer that is overwritten by
     * the next computeGeometry() call.
     */
    public get vertices(): Float32Array {
        return this._vertices.subarray(0, this._vertexCount * 3);
    }

    /**
     * Returns the vertex normals generated by the most recent computeGeometry()
     * call as an exact-length view (3 floats per vertex). Normals are normalised.
     *
     * NOTE: The returned view aliases an internal buffer that is overwritten by
     * the next computeGeometry() call.
     */
    public get normals(): Float32Array {
        return this._normals.subarray(0, this._vertexCount * 3);
    }

    /**
     * Returns the triangle indices generated by the most recent computeGeometry()
     * call as an exact-length view (3 indices per triangle).
     *
     * NOTE: The returned view aliases an internal buffer that is overwritten by
     * the next computeGeometry() call.
     */
    public get indices(): Uint32Array {
        return this._indices.subarray(0, this._indexCount);
    }

    /**
     * Returns the number of vertices generated by the most recent
     * computeGeometry() call.
     */
    public get vertexCount(): number {
        return this._vertexCount;
    }

    /**
     * Returns the number of indices generated by the most recent
     * computeGeometry() call.
     */
    public get indexCount(): number {
        return this._indexCount;
    }

    /**
     * Computes a smooth surface mesh for all BitVoxels in the given VoxelChunk.
     * Neighbouring chunks in the VoxelWorld are sampled so the generated surface
     * is watertight across chunk seams.
     *
     * @param center - The VoxelChunk for which geometry is being generated.
     * @param world - The VoxelWorld instance used to query neighbouring chunks.
     * @param smoothing - (Optional) The number of field smoothing passes between 0
     * and MAX_SMOOTHING. Defaults to 0 (classic surface nets).
     * @param flipped - (Optional) Whether to flip the triangle winding order, for
     * renderers with an opposite front-face convention. Defaults to false.
     */
    public computeGeometry(center: VoxelChunk, world: VoxelWorld, smoothing = 0, flipped = false): void {
        this._vertexCount = 0;
        this._indexCount = 0;
        this._degenerateNormalCount = 0;

        const passes: number = Math.min(Math.max(smoothing | 0, 0), VoxelSmoothGeometry.MAX_SMOOTHING);
        const margin: number = 1 + passes;

        // sample the occupancy field from the center chunk and its neighbours
        const negativeNeighbours: boolean[] = this._SampleField(center, world, margin);

        // blur the field for each smoothing pass
        for (let pass = 0; pass < passes; pass++) {
            this._SmoothField(margin);
        }

        // contour the field - generate one vertex per surface cell
        this._ComputeVertices(margin);

        // connect surface cell vertices into quads across sign-change edges
        this._ComputeQuads(margin, negativeNeighbours, flipped);

        // resolve normals for cells with a degenerate field gradient
        if (this._degenerateNormalCount > 0) {
            this._ComputeFallbackNormals();
        }
    }

    /**
     * Samples the occupancy field for the chunk and a margin of surrounding
     * BitVoxels read from neighbouring chunks. Missing chunks sample as empty.
     *
     * @param center - The VoxelChunk being contoured.
     * @param world - The VoxelWorld used to query neighbouring chunks.
     * @param margin - The number of samples to read beyond the chunk on each side.
     * @returns - Existence flags for the -x, -y and -z neighbouring chunks, used
     * for seam quad ownership.
     */
    private _SampleField(center: VoxelChunk, world: VoxelWorld, margin: number): boolean[] {
        const dims: number = BVXLayer.DIMS;
        const fieldDims: number = VoxelSmoothGeometry._FIELD_DIMS;
        const field: Float32Array = this._field;
        const centerKey: MortonKey = center.key;
        const tmpKey: MortonKey = VoxelSmoothGeometry.TMP_MK;

        // gather the 3x3x3 neighbourhood of chunk BitVoxel storages (null = missing)
        const neighbourhood: (Uint32Array | null)[] = new Array<Uint32Array | null>(27);

        for (let ox = -1; ox <= 1; ox++) {
            for (let oy = -1; oy <= 1; oy++) {
                for (let oz = -1; oz <= 1; oz++) {
                    const slot: number = ((ox + 1) * 3 + (oy + 1)) * 3 + (oz + 1);

                    if (ox === 0 && oy === 0 && oz === 0) {
                        neighbourhood[slot] = center.layer.bitArray.elements;

                        continue;
                    }

                    MortonKey.from(centerKey.x + ox, centerKey.y + oy, centerKey.z + oz, tmpKey);

                    const chunk: VoxelChunk | null = world.get(tmpKey);
                    neighbourhood[slot] = chunk !== null ? chunk.layer.bitArray.elements : null;
                }
            }
        }

        field.fill(0.0);

        // fill the field with 0/1 occupancy for samples in [-margin, dims + margin)
        const min: number = -margin;
        const max: number = dims + margin;

        for (let sx = min; sx < max; sx++) {
            const cx: number = sx >> 4;
            const lx: number = sx & 15;

            for (let sy = min; sy < max; sy++) {
                const cy: number = sy >> 4;
                const ly: number = sy & 15;

                for (let sz = min; sz < max; sz++) {
                    const cz: number = sz >> 4;
                    const lz: number = sz & 15;

                    const elements: Uint32Array | null = neighbourhood[((cx + 1) * 3 + (cy + 1)) * 3 + (cz + 1)];

                    if (elements === null) {
                        continue;
                    }

                    // BitVoxel index within the owning chunk
                    const index: number = ((lx >> 2) << 10) | ((ly >> 2) << 8) | ((lz >> 2) << 6) | ((lx & 3) << 4) | ((ly & 3) << 2) | (lz & 3);
                    const state: number = (elements[index >> 5] >>> (index & 31)) & 1;

                    if (state !== 0) {
                        field[((sx + margin) * fieldDims + (sy + margin)) * fieldDims + (sz + margin)] = 1.0;
                    }
                }
            }
        }

        // existence flags for the negative-side neighbours (seam quad ownership)
        const xnExists: boolean = world.get(MortonKey.from(centerKey.x - 1, centerKey.y, centerKey.z, tmpKey)) !== null;
        const ynExists: boolean = world.get(MortonKey.from(centerKey.x, centerKey.y - 1, centerKey.z, tmpKey)) !== null;
        const znExists: boolean = world.get(MortonKey.from(centerKey.x, centerKey.y, centerKey.z - 1, tmpKey)) !== null;

        return [xnExists, ynExists, znExists];
    }

    /**
     * Applies a single separable 3-tap blur pass (0.25, 0.5, 0.25) to the field
     * along each axis. Buffer edges are clamped - only samples within the active
     * margin remain exact, which is guaranteed by the margin sizing.
     *
     * @param margin - The active field margin, used to bound the blur region.
     */
    private _SmoothField(margin: number): void {
        const dims: number = BVXLayer.DIMS;
        const fieldDims: number = VoxelSmoothGeometry._FIELD_DIMS;
        const field: Float32Array = this._field;
        const scratch: Float32Array = this._fieldScratch;

        const min = 0;
        const max: number = dims + (2 * margin);

        const strides: number[] = [fieldDims * fieldDims, fieldDims, 1];

        // blur each axis in sequence, ping-ponging between field and scratch
        for (let axis = 0; axis < 3; axis++) {
            const stride: number = strides[axis];

            for (let x = min; x < max; x++) {
                for (let y = min; y < max; y++) {
                    for (let z = min; z < max; z++) {
                        const index: number = (x * fieldDims + y) * fieldDims + z;

                        // clamp reads at the buffer edges of the blur axis
                        const axisCoord: number = axis === 0 ? x : (axis === 1 ? y : z);
                        const prev: number = axisCoord > min ? field[index - stride] : field[index];
                        const next: number = axisCoord < (max - 1) ? field[index + stride] : field[index];

                        scratch[index] = (0.25 * prev) + (0.5 * field[index]) + (0.25 * next);
                    }
                }
            }

            field.set(scratch);
        }
    }

    /**
     * Generates one vertex for every surface cell of the field. A surface cell is
     * a dual cell between 8 field samples whose occupancy states differ. The
     * vertex is placed at the centroid of the iso-level crossings along the cell
     * edges, and its normal is the negated field gradient at the cell.
     *
     * @param margin - The active field margin.
     */
    private _ComputeVertices(margin: number): void {
        const fieldDims: number = VoxelSmoothGeometry._FIELD_DIMS;
        const cellDims: number = VoxelSmoothGeometry._CELL_DIMS;
        const iso: number = VoxelSmoothGeometry._ISO_LEVEL;
        const scale: number = VoxelSmoothGeometry.BIT_VOXEL_SIZE;

        const field: Float32Array = this._field;
        const cellVertex: Int32Array = this._cellVertex;
        const vertices: Float32Array = this._vertices;
        const normals: Float32Array = this._normals;

        cellVertex.fill(-1);

        let vertexCount = 0;

        // cells with min-corner from -1 to dims - 1 (inclusive) on each axis
        for (let cx = -1; cx < cellDims - 1; cx++) {
            for (let cy = -1; cy < cellDims - 1; cy++) {
                for (let cz = -1; cz < cellDims - 1; cz++) {
                    const baseIndex: number = ((cx + margin) * fieldDims + (cy + margin)) * fieldDims + (cz + margin);

                    // the 8 corner samples of the dual cell, indexed as dx | dy << 1 | dz << 2
                    const f0: number = field[baseIndex];
                    const f1: number = field[baseIndex + (fieldDims * fieldDims)];
                    const f2: number = field[baseIndex + fieldDims];
                    const f3: number = field[baseIndex + (fieldDims * fieldDims) + fieldDims];
                    const f4: number = field[baseIndex + 1];
                    const f5: number = field[baseIndex + (fieldDims * fieldDims) + 1];
                    const f6: number = field[baseIndex + fieldDims + 1];
                    const f7: number = field[baseIndex + (fieldDims * fieldDims) + fieldDims + 1];

                    // corner occupancy mask - skip cells fully inside or outside
                    const mask: number =
                        (f0 >= iso ? 1 : 0) |
                        (f1 >= iso ? 2 : 0) |
                        (f2 >= iso ? 4 : 0) |
                        (f3 >= iso ? 8 : 0) |
                        (f4 >= iso ? 16 : 0) |
                        (f5 >= iso ? 32 : 0) |
                        (f6 >= iso ? 64 : 0) |
                        (f7 >= iso ? 128 : 0);

                    if (mask === 0 || mask === 255) {
                        continue;
                    }

                    // accumulate the iso-level crossing offsets of the 12 cell edges
                    let px = 0.0;
                    let py = 0.0;
                    let pz = 0.0;
                    let crossings = 0;

                    // edges along x - corner pairs (0,1) (2,3) (4,5) (6,7)
                    if ((f0 >= iso) !== (f1 >= iso)) { const t: number = (iso - f0) / (f1 - f0); px += t; crossings++; }
                    if ((f2 >= iso) !== (f3 >= iso)) { const t: number = (iso - f2) / (f3 - f2); px += t; py += 1.0; crossings++; }
                    if ((f4 >= iso) !== (f5 >= iso)) { const t: number = (iso - f4) / (f5 - f4); px += t; pz += 1.0; crossings++; }
                    if ((f6 >= iso) !== (f7 >= iso)) { const t: number = (iso - f6) / (f7 - f6); px += t; py += 1.0; pz += 1.0; crossings++; }

                    // edges along y - corner pairs (0,2) (1,3) (4,6) (5,7)
                    if ((f0 >= iso) !== (f2 >= iso)) { const t: number = (iso - f0) / (f2 - f0); py += t; crossings++; }
                    if ((f1 >= iso) !== (f3 >= iso)) { const t: number = (iso - f1) / (f3 - f1); py += t; px += 1.0; crossings++; }
                    if ((f4 >= iso) !== (f6 >= iso)) { const t: number = (iso - f4) / (f6 - f4); py += t; pz += 1.0; crossings++; }
                    if ((f5 >= iso) !== (f7 >= iso)) { const t: number = (iso - f5) / (f7 - f5); py += t; px += 1.0; pz += 1.0; crossings++; }

                    // edges along z - corner pairs (0,4) (1,5) (2,6) (3,7)
                    if ((f0 >= iso) !== (f4 >= iso)) { const t: number = (iso - f0) / (f4 - f0); pz += t; crossings++; }
                    if ((f1 >= iso) !== (f5 >= iso)) { const t: number = (iso - f1) / (f5 - f1); pz += t; px += 1.0; crossings++; }
                    if ((f2 >= iso) !== (f6 >= iso)) { const t: number = (iso - f2) / (f6 - f2); pz += t; py += 1.0; crossings++; }
                    if ((f3 >= iso) !== (f7 >= iso)) { const t: number = (iso - f3) / (f7 - f3); pz += t; px += 1.0; py += 1.0; crossings++; }

                    const inv: number = 1.0 / crossings;

                    // vertex position in BitVoxel units - samples sit at coordinate + 0.5
                    const vx: number = (cx + (px * inv) + 0.5) * scale;
                    const vy: number = (cy + (py * inv) + 0.5) * scale;
                    const vz: number = (cz + (pz * inv) + 0.5) * scale;

                    // the field gradient at the cell - local to the 8 samples, which
                    // keeps normals consistent on both sides of a chunk seam
                    const gx: number = (f1 + f3 + f5 + f7) - (f0 + f2 + f4 + f6);
                    const gy: number = (f2 + f3 + f6 + f7) - (f0 + f1 + f4 + f5);
                    const gz: number = (f4 + f5 + f6 + f7) - (f0 + f1 + f2 + f3);

                    const gradientLength: number = Math.sqrt((gx * gx) + (gy * gy) + (gz * gz));

                    const writeIndex: number = vertexCount * 3;

                    vertices[writeIndex] = vx;
                    vertices[writeIndex + 1] = vy;
                    vertices[writeIndex + 2] = vz;

                    if (gradientLength > 1e-8) {
                        // the normal points from solid (1) towards empty (0)
                        const gradientInv: number = -1.0 / gradientLength;

                        normals[writeIndex] = gx * gradientInv;
                        normals[writeIndex + 1] = gy * gradientInv;
                        normals[writeIndex + 2] = gz * gradientInv;
                    }
                    else {
                        // degenerate gradient - resolved from triangle normals later
                        normals[writeIndex] = 0.0;
                        normals[writeIndex + 1] = 0.0;
                        normals[writeIndex + 2] = 0.0;

                        this._degenerateNormalCount++;
                    }

                    cellVertex[((cx + 1) * cellDims + (cy + 1)) * cellDims + (cz + 1)] = vertexCount;
                    vertexCount++;
                }
            }
        }

        this._vertexCount = vertexCount;
    }

    /**
     * Emits quads for every field edge whose two samples straddle the iso-level.
     * Each quad connects the vertices of the 4 surface cells sharing the edge.
     *
     * Seam ownership: edges on the negative chunk boundary are skipped when the
     * negative-side neighbouring chunk exists, as that chunk emits the identical
     * quad itself. This keeps chunk seams free of duplicate geometry.
     *
     * @param margin - The active field margin.
     * @param negativeNeighbours - Existence flags for the -x, -y and -z neighbours.
     * @param flipped - Whether to flip the triangle winding order.
     */
    private _ComputeQuads(margin: number, negativeNeighbours: boolean[], flipped: boolean): void {
        const dims: number = BVXLayer.DIMS;
        const fieldDims: number = VoxelSmoothGeometry._FIELD_DIMS;
        const cellDims: number = VoxelSmoothGeometry._CELL_DIMS;
        const iso: number = VoxelSmoothGeometry._ISO_LEVEL;

        const field: Float32Array = this._field;
        const cellVertex: Int32Array = this._cellVertex;
        const indices: Uint32Array = this._indices;

        let indexCount: number = this._indexCount;

        const fieldStrides: number[] = [fieldDims * fieldDims, fieldDims, 1];

        for (let axis = 0; axis < 3; axis++) {
            const fieldStride: number = fieldStrides[axis];

            // the other two axes forming the quad ring around the edge
            const axisU: number = axis === 0 ? 1 : 0;
            const axisV: number = axis === 2 ? 1 : 2;

            // cell map strides for the ring axes
            const strideU: number = axisU === 0 ? cellDims * cellDims : (axisU === 1 ? cellDims : 1);
            const strideV: number = axisV === 1 ? cellDims : 1;

            // edges on the negative seam are owned by the negative-side neighbour
            const skipNegativeSeam: boolean = negativeNeighbours[axis];

            const edge: number[] = [0, 0, 0];

            // the edge axis spans -1 to dims - 1, the ring axes span 0 to dims - 1
            for (let d = -1; d < dims; d++) {
                if (d === -1 && skipNegativeSeam) {
                    continue;
                }

                edge[axis] = d;

                for (let u = 0; u < dims; u++) {
                    edge[axisU] = u;

                    for (let v = 0; v < dims; v++) {
                        edge[axisV] = v;

                        const fieldIndex: number = ((edge[0] + margin) * fieldDims + (edge[1] + margin)) * fieldDims + (edge[2] + margin);

                        const a: number = field[fieldIndex];
                        const b: number = field[fieldIndex + fieldStride];

                        const solidA: boolean = a >= iso;
                        const solidB: boolean = b >= iso;

                        // no surface crosses this edge
                        if (solidA === solidB) {
                            continue;
                        }

                        // the 4 surface cells sharing this edge - the cell map is
                        // offset by +1 so cell -1 maps to slot 0
                        const cellBase: number = ((edge[0] + 1) * cellDims + (edge[1] + 1)) * cellDims + (edge[2] + 1);

                        const v00: number = cellVertex[cellBase - strideU - strideV];
                        const v10: number = cellVertex[cellBase - strideV];
                        const v11: number = cellVertex[cellBase];
                        const v01: number = cellVertex[cellBase - strideU];

                        // quad winding - faces the empty sample. The y axis ring has
                        // opposite parity to the x and z rings.
                        let facePositive: boolean = solidA;

                        if (axis === 1) {
                            facePositive = !facePositive;
                        }

                        if (flipped) {
                            facePositive = !facePositive;
                        }

                        if (facePositive) {
                            indices[indexCount] = v00;
                            indices[indexCount + 1] = v10;
                            indices[indexCount + 2] = v11;
                            indices[indexCount + 3] = v00;
                            indices[indexCount + 4] = v11;
                            indices[indexCount + 5] = v01;
                        }
                        else {
                            indices[indexCount] = v00;
                            indices[indexCount + 1] = v01;
                            indices[indexCount + 2] = v11;
                            indices[indexCount + 3] = v00;
                            indices[indexCount + 4] = v11;
                            indices[indexCount + 5] = v10;
                        }

                        indexCount += 6;
                    }
                }
            }
        }

        this._indexCount = indexCount;
    }

    /**
     * Resolves normals for vertices whose field gradient was degenerate (zero) by
     * accumulating the geometric normals of their connected triangles.
     */
    private _ComputeFallbackNormals(): void {
        const vertices: Float32Array = this._vertices;
        const normals: Float32Array = this._normals;
        const indices: Uint32Array = this._indices;
        const indexCount: number = this._indexCount;

        for (let i = 0; i < indexCount; i += 3) {
            const ia: number = indices[i] * 3;
            const ib: number = indices[i + 1] * 3;
            const ic: number = indices[i + 2] * 3;

            // skip triangles that touch no degenerate vertices
            const aDegenerate: boolean = normals[ia] === 0.0 && normals[ia + 1] === 0.0 && normals[ia + 2] === 0.0;
            const bDegenerate: boolean = normals[ib] === 0.0 && normals[ib + 1] === 0.0 && normals[ib + 2] === 0.0;
            const cDegenerate: boolean = normals[ic] === 0.0 && normals[ic + 1] === 0.0 && normals[ic + 2] === 0.0;

            if (!aDegenerate && !bDegenerate && !cDegenerate) {
                continue;
            }

            // geometric normal of the triangle
            const abx: number = vertices[ib] - vertices[ia];
            const aby: number = vertices[ib + 1] - vertices[ia + 1];
            const abz: number = vertices[ib + 2] - vertices[ia + 2];

            const acx: number = vertices[ic] - vertices[ia];
            const acy: number = vertices[ic + 1] - vertices[ia + 1];
            const acz: number = vertices[ic + 2] - vertices[ia + 2];

            const nx: number = (aby * acz) - (abz * acy);
            const ny: number = (abz * acx) - (abx * acz);
            const nz: number = (abx * acy) - (aby * acx);

            const length: number = Math.sqrt((nx * nx) + (ny * ny) + (nz * nz));

            if (length <= 1e-12) {
                continue;
            }

            const inv: number = 1.0 / length;

            // accumulate scaled normals into the degenerate vertices only - the
            // final normalisation happens below
            if (aDegenerate) { normals[ia] += nx * inv; normals[ia + 1] += ny * inv; normals[ia + 2] += nz * inv; }
            if (bDegenerate) { normals[ib] += nx * inv; normals[ib + 1] += ny * inv; normals[ib + 2] += nz * inv; }
            if (cDegenerate) { normals[ic] += nx * inv; normals[ic + 1] += ny * inv; normals[ic + 2] += nz * inv; }
        }

        // normalise the accumulated normals
        const vertexCount: number = this._vertexCount;

        for (let i = 0; i < vertexCount; i++) {
            const index: number = i * 3;

            const nx: number = normals[index];
            const ny: number = normals[index + 1];
            const nz: number = normals[index + 2];

            const length: number = Math.sqrt((nx * nx) + (ny * ny) + (nz * nz));

            if (length > 1e-12 && Math.abs(length - 1.0) > 1e-6) {
                const inv: number = 1.0 / length;

                normals[index] = nx * inv;
                normals[index + 1] = ny * inv;
                normals[index + 2] = nz * inv;
            }
            else if (length <= 1e-12) {
                // isolated degenerate vertex - default to an up-facing normal
                normals[index] = 0.0;
                normals[index + 1] = 1.0;
                normals[index + 2] = 0.0;
            }
        }
    }
}
