name: Run Jest Test Coverage
on: [push]
jobs:
  run-jest-tests:
    name: Run Unit Tests with Jest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm dependencies
        run: npm --prefix ./bvx-kit install ./bvx-kit
      - name: Run Jest tests in CI mode
        run: npm --prefix ./bvx-kit run test:ci
      - name: Run ESLint
        run: npm --prefix ./bvx-kit run lint